language:
  - c
  - cpp
compiler:
  - gcc
notifications:
  email: false
cache:
  apt: true
before_install: 
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-arm-none-eabi -qq

