language:
  - c
  - cpp
compiler:
  - gcc
notifications:
  email: false
cache:
  apt: true
before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install python-setuptools  cmake build-essential ninja-build python-dev python-pip libffi-dev libssl-dev -qq
  - sudo apt-get install gcc-arm-none-eabi -qq
  - sudo pip install yotta -q
script:
  - yotta target frdm-k64f-gcc
  - yotta build
